# Specifies what build spec version this file is.
# This helps AWS CodePipeline parse the file correctly.
# Keep this at 0.2
version: 0.2
# We can listen for specific phases and execute commands per phase.
phases:
  # The build server won't have access to our node_modules folder
  # This is because we have it inside of our .gitignore file
  # To give our build server access, we can simply run "npm install"
  pre_build:
    commands:
      - yarn install
      - npm install --legacy-peer-deps
  build:
   commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id=E23RYE2LFE8OR4 --paths '/*'
# Artifacts will specify what files will be uploaded to s3
# This will include all files within the "build" folder
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
